basePath: /
host: localhost:3000
info:
  contact: {}
  license:
    name: GPL v3.0
  title: openstats API
  version: "1.0"
paths:
  /auth/sign-up:
    post:
      description: Authenticates the user and creates a new session for the user
      responses: {}
      summary: Create a new user session
securityDefinitions:
  ApiTokenAuth:
    description: JWT authentication, intended for automated and developer use of the
      API
    in: header
    name: Authorization
    type: apiKey
  SessionAuth:
    description: Cookie-based authentication, intended for user interactions on the
      website
    in: cookie
    name: session_id
    type: apiKey
swagger: "2.0"
